[package]
name = "app"
version = "0.4.9"
description = "A minimalist image viewer"
authors = [ "sprout2000" ]
license = "MIT"
repository = "https://github.com/sprout2000/leafview-tauri/"
default-run = "app"
edition = "2021"
rust-version = "1.62"

[build-dependencies]
tauri-build = { version = "1.0.4", features = [] }

[dependencies]
infer = "0.9.0"
serde_json = "1.0.82"
serde = { version = "1.0.139", features = [ "derive" ] }
tauri = { version = "1.0.4", features = ["dialog-open", "path-all", "protocol-asset", "shell-open", "window-set-title"] }
trash = "2.1.5"
json-gettext = "4.0.3"
sys-locale = "0.2.1"

[dependencies.tauri-plugin-window-state]
git = "https://github.com/tauri-apps/tauri-plugin-window-state"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
