[package]
name = "app"
version = "0.2.4"
description = "A minimalist image viewer"
authors = [ "sprout2000" ]
license = "MIT"
repository = "https://github.com/sprout2000/leafview/"
default-run = "app"
edition = "2021"
rust-version = "1.59"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.5", features = [] }

[dependencies]
infer = "0.7.0"
json-gettext = "4.0.1"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = [ "derive" ] }
sys-locale = "0.2.0"
tauri = { version = "1.0.0-rc.6", features = ["dialog-open", "path-all", "protocol-asset", "shell-open", "window-set-title"] }
trash = "2.0.4"

[dependencies.tauri-plugin-window-state]
git = "https://github.com/tauri-apps/tauri-plugin-window-state"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
