[package]
name = "app"
version = "0.8.7"
description = "A minimalist image viewer"
authors = [ "sprout2000" ]
license = "MIT"
repository = "https://github.com/sprout2000/leafview-tauri/"
default-run = "app"
edition = "2021"
rust-version = "1.65"

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
infer = "0.12.0"
serde_json = "1.0.91"
serde = { version = "1.0.152", features = [ "derive" ] }
tauri = { version = "1.2.4", features = ["dialog-open", "path-all", "protocol-asset", "shell-open", "window-set-title"] }
time = "0.3.17"
trash = "3.0.0"
json-gettext = "4.0.5"
sys-locale = "0.2.3"
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "dev" }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
