[package]
name = "app"
version = "0.3.11"
description = "A minimalist image viewer"
authors = [ "sprout2000" ]
license = "MIT"
repository = "https://github.com/sprout2000/leafview-tauri/"
default-run = "app"
edition = "2021"
rust-version = "1.61"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.13", features = [] }

[dependencies]
infer = "0.8.1"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = [ "derive" ] }
tauri = { version = "1.0.0-rc.15", features = ["dialog-open", "path-all", "protocol-asset", "shell-open", "window-set-title"] }
trash = "2.1.4"
json-gettext = "4.0.3"
sys-locale = "0.2.0"

[dependencies.tauri-plugin-window-state]
git = "https://github.com/tauri-apps/tauri-plugin-window-state"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
